# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590f99749a0ad40ea0b49b113a4c57aba5801dfee27d8c34a9cffec87456558e80cd050a2075429204cbb7532361c3b42622156a6fa5006aa67405a4a0a2753e

test:
  secret_key_base: 7e368e39928e8f14e42f7c9de20178c27c65c6072ce5e5e1ff37b22682a66e46c752f1ae72881815d0996c8c26fde09cd81011e1db6e9c803d11c88fe6aed1b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
